//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonService_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolonAppointment
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string ClientPhone { get; set; }
        public Nullable<int> SalonServicesId { get; set; }
        public Nullable<int> SalonFacilitatorId { get; set; }
        public Nullable<int> BillAmount { get; set; }
        public Nullable<System.DateTime> AppointDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsServed { get; set; }
    }
}
